ATOM     = "http://www.w3.org/2005/Atom"
GEO      = "http://www.georss.org/georss"
PS       = "http://jabber.org/protocol/pubsub"
PS_EVENT = "http://jabber.org/protocol/pubsub#event"
SF       = "http://superfeedr.com/xmpp-pubsub-ext"
